### ISSUE TITLE
Example for paginated query

### ISSUE THREAD

**Issue by martinformi** [line/kotlin-jdsl#184] opened 2023-02-01 15:36 UTC
I am trying to have paginated requests/results but I am not able to find one working example. Could you please provide it? I expect `.pageQuery` is used.

**Comment by cj848** [comment] 2023-02-11 00:19
If you submit it as a minimal reproducible code sample github project, I'll check it out. Currently there is no problem within my project.

**Comment by cj848** [comment] 2023-02-11 00:19
Basically, pageQuery operates the same as the rest of the select side except for groupBy and fetch. Is there a reason you need a separate example apart from the example in readme.md?

**Comment by cj848** [comment] 2023-02-18 11:48
Since there is no answer, I will close the issue. If you have any questions, please reopen and comment again.

**Closed by cj848** 2023-02-18 11:48 UTC
