### ISSUE TITLE
Support for spring boot 3.0

### ISSUE THREAD

**Issue by martinformi** [line/kotlin-jdsl#195] opened 2023-02-15 12:38 UTC
Spring Boot 3.0 is using `jakarta` namespace instead of `javax`. Also hibernate core 6.1.6 itself is in `jakarta` namespace. However `FetchDsl` is using `import javax.persistence.criteria.JoinType`. How can I fix this?

EDIT: Use `*-jakarta` packages instead.

**Comment by cj848** [comment] 2023-02-18 11:47
Already our project supports 3.0. Check the examples/spring-boot-3 folder. If the problem is reproducible, please open a minimal reproducible project on github and we'll check it out.

**Comment by GunnGu** [comment] 2023-02-27 03:26
Currently, we have the same issue.
the DSL uses JoinType from "javax" not "jakarta". if we use "javax" JoinType, maybe it can work around the problem, but I don't know if this is the right approach.

https://github.com/line/kotlin-jdsl/blob/d8d6cd83168dad239a403a1728500b3f1bbde28c/query-jakarta/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/from/FetchDsl.kt#L4

**Comment by cj848** [comment] 2023-03-04 22:23
I will close the issue as there are no further comments.

**Closed by cj848** 2023-03-04 22:23 UTC
